### PR TITLE
Upgrade numpy, add Py3.10, remove Py3.6

### LINKED ISSUE #152: Cannot build with Python 3.10 due to numpy version restriction
`setup.py` has:

    install_requires=[
        'numpy    >= 1.15, < 1.20',
        'scipy    >= 1.2',

This prevents splipy from installing with Python 3.10 since the Numpy version that supports Py3.10 is 1.21.  I removed this restriction from `setup.py` (changed to `'numpy    >= 1.15'`) and Splipy seems to build and work just fine.  Can the max. numpy version be bumped up, or removed, from `setup.py`?

### PR DESCRIPTION
**Pull request by TheBB**

### CODE REVIEW

**Comment by TheBB** [comment]
Image and 3DM tests will be disabled in the CI pipeline for now. Images can be reenabled once Github Actions move MacOS to v11 (no Python 3.10 builds for OpenCV on earlier MacOSes). I also couldn't find a version of Rhino3DM that is pre-built for all the configurations we want.

**Comment by VikingScientist** [comment]
Is disabling of tests a binary decision? Do we have to disable them for all configurations if builds are missing for only some configurations?

**Comment by TheBB** [comment]
No, it's just a matter of convenience.

**Comment by TheBB** [comment]
Fixed in #154

**Pull request merged**
