### PR TITLE
IFEM SplineModel output

### PR DESCRIPTION
**Pull request by TheBB**
Like a phoenix from the ashes of #7. 

This one is not marked WIP because I just used it on the bridge and it worked with minor changes.

### CODE REVIEW

**Comment by TheBB** [comment]
Fixed CI failure and rebased on #119.

**Comment by TheBB** [comment]
Apparently lxml is a little tricky to get on Windows. It's a wrapper around libxml so that's understandable. Changed to use manual XML generation. (Python has an xml module but it doesn't do pretty printing.)

**Comment by VikingScientist** [comment]
What happens if you try and dump a model which is not right-handed? I.e. with negative Jacobian.

Missing unit test

Merge conflicts.

**Comment by TheBB** [comment]
Added tests, copied from IFEM thanks to @akva2. This includes left-handed patches, so everything should work as expected.

**Comment by TheBB** [comment]
@VikingScientist this is ready

**Pull request merged**
