### PR TITLE
add 3dm reader

### PR DESCRIPTION
**Pull request by akva2**
This is horrible and ugly but does work at least. Not really tested in splipy clothes but it worked in a standalone test.

Meant as a starting poing

### CODE REVIEW

**Comment by VikingScientist** [comment]
Why does the checks fail on linux distro, while it works without problems on my linux installation?

**Comment by akva2** [comment]
it failed due to gcc5 being too old.

**Comment by TheBB** [comment]
Travis is rapidly becoming increasingly useless. I've been trying to move to GH actions instead. Ran into some error so I temporarily gave up.

**Comment by TheBB** [comment]
Of course it wouldn't have been a problem if the rhino3dm package offered prebuilt linux wheels, but they don't.

https://pypi.org/project/rhino3dm/#files

**Comment by VikingScientist** [comment]
> Of course it wouldn't have been a problem if the rhino3dm package offered prebuilt linux wheels, but they don't.
> 
> https://pypi.org/project/rhino3dm/#files

There have been two new releases since last time this PR was discussed; during the last week actually. From what I can understand this covers linux distributions, but is limited to python 3.8 and python 3.9.

**Comment by VikingScientist** [comment]
@akva2 : could you rebase this on master and see if that will trigger a rerun of the CI

**Pull request merged**
