### PR TITLE
Fix push_documentation.py

### PR DESCRIPTION
**Pull request by TheBB**
Some paths were different from the repo where we got this from, it seems.

### CODE REVIEW

**Comment by VikingScientist** [comment]
And it works now? Have you tested it? I see that the bug from #48 is still present

**Comment by TheBB** [comment]
Well I just tried to fix the push script, I didn't actually run or update anything. But #48 is fixed now I think.

**Comment by VikingScientist** [comment]
Tried running the script and got the following error message:
```
Cloning into '/tmp/tmp034e9tog'...
done.
error: pathspec 'gh-pages' did not match any file(s) known to git.
Traceback (most recent call last):
  File "./push_documentation.py", line 14, in <module>
    run(['git', 'checkout', 'gh-pages'], cwd=tgt, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'checkout', 'gh-pages']' returned non-zero exit status 1
```
All documentation pages are up now, so I guess we can close #48

**Comment by TheBB** [comment]
You need a local branch called `gh-pages`.

**Comment by TheBB** [comment]
Also you need a remote called `upstream` to push to.

**Pull request merged**
