### PR TITLE
Derivative splines

### PR DESCRIPTION
**Pull request by VikingScientist**
Derivatives of splines are themselves splines. This allows for an explicit construction of these objects.

It basically allows for this operation here:
```python
  surf2 = surf.get_derivative_spline(direction='u') # type(surf2) == Surface
  surf3 = surf.get_derivative_spline(direction='v')
  u    = np.linspace(surf.start(0), surf.end(0), 7) # evaluation points
  v    = np.linspace(surf.start(1), surf.end(1), 7)
  du   = surf.derivative(u,v, d=(1,0))
  du2  = surf2(u,v) # du == du2 everywhere
  dv   = surf.derivative(u,v, d=(0,1))
  dv2  = surf3(u,v) # dv == dv2
```

### CODE REVIEW

**Comment by TheBB** [comment]
This looks good but I would rest a bit easier if the `transpose_fix` hack was fully dimension agnostic. We already have one instance of that in the code. I suggest we replace both with something like this:

```python
def transpose_fix(pardim, direction):
   ret = list(range(1, pardim+1))
   ret.insert(direction, 0)
   return tuple(ret)
```

From what I can tell this will work as expected.

**Comment by TheBB** [comment]
IOW I'm suggesting putting this on top https://github.com/TheBB/Splipy/commit/fd2cd93b4c387529939770749d74819f61a53b8d

**Comment by VikingScientist** [comment]
Fixed

**Comment by TheBB** [comment]
This one is in!

**Pull request closed without merging**
